


services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    container_name: AI
    volumes:   
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
    expose:
      - "8000"
    restart : always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=994966161hH
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - .:/code


